### ISSUE TITLE
Status listing errors out when used with Python3 3.10.12

### ISSUE THREAD

**Issue by xard-dev** [goncalor/8bitdo-kbd-mapper#3]
The status listing fails to following error when the program is used with Python3 3.10.12: 
`TypeError: from_bytes() missing required argument 'byteorder' (pos 2)`

Following patch which adds the byte order parameter mitigated this issue:
```
index 9548b22..4284cba 100644
--- a/src/eightbdkbd/client.py
+++ b/src/eightbdkbd/client.py
@@ -91,7 +91,7 @@ class EightBDKdb:
         r = self.read_check_start(MAPPING)
 
         hid = r[3:6]
-        hid_int = int.from_bytes(hid)
+        hid_int = int.from_bytes(hid, byteorder='big')
         for name, val in keys.USAGE.items():
             if val[0] == hid_int:
                 return name
```

**Comment by goncalor** [comment]
Hey. Thanks. I see [from the documentation](https://docs.python.org/3.12/library/stdtypes.html#int.from_bytes) that before 3.11 there was no default byte ordering argument value.

I'll patch this later.

**Comment by goncalor** [comment]
Patched. Thank you!
